spring.application.name=bmcd134_D288
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.data.rest.base-path=/api
spring.jackson.parser.allow-comments=true
logging.level.org.springframework=info

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.check_nullability=true
